-- Seed: countries with FATF status, sanctions, dominant payment methods
-- fatf_status: compliant | grey_list | black_list
-- is_sanctioned: true for OFAC/UN primary sanctioned countries

insert into countries (code, name, name_ru, region, fatf_status, is_sanctioned, sanction_details, dominant_payment_methods) values

-- EUROPE (EU)
('AT', 'Austria', 'Австрия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('BE', 'Belgium', 'Бельгия', 'eu', 'compliant', false, null, '{bancontact,visa_mastercard,sepa}'),
('BG', 'Bulgaria', 'Болгария', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('HR', 'Croatia', 'Хорватия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('CY', 'Cyprus', 'Кипр', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('CZ', 'Czech Republic', 'Чехия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('DK', 'Denmark', 'Дания', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('EE', 'Estonia', 'Эстония', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('FI', 'Finland', 'Финляндия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('FR', 'France', 'Франция', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('DE', 'Germany', 'Германия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('GR', 'Greece', 'Греция', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('HU', 'Hungary', 'Венгрия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('IE', 'Ireland', 'Ирландия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('IT', 'Italy', 'Италия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('LV', 'Latvia', 'Латвия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('LT', 'Lithuania', 'Литва', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('LU', 'Luxembourg', 'Люксембург', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('MT', 'Malta', 'Мальта', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('NL', 'Netherlands', 'Нидерланды', 'eu', 'compliant', false, null, '{ideal,visa_mastercard,sepa}'),
('PL', 'Poland', 'Польша', 'eu', 'compliant', false, null, '{blik,visa_mastercard,sepa}'),
('PT', 'Portugal', 'Португалия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('RO', 'Romania', 'Румыния', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('SK', 'Slovakia', 'Словакия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('SI', 'Slovenia', 'Словения', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('ES', 'Spain', 'Испания', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('SE', 'Sweden', 'Швеция', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('GB', 'United Kingdom', 'Великобритания', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('CH', 'Switzerland', 'Швейцария', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('NO', 'Norway', 'Норвегия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('IS', 'Iceland', 'Исландия', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('GI', 'Gibraltar', 'Гибралтар', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),
('IM', 'Isle of Man', 'Остров Мэн', 'eu', 'compliant', false, null, '{visa_mastercard,sepa}'),

-- NORTH AMERICA
('US', 'United States', 'США', 'na', 'compliant', false, null, '{visa_mastercard,ach,paypal}'),
('CA', 'Canada', 'Канада', 'na', 'compliant', false, null, '{visa_mastercard,ach}'),
('MX', 'Mexico', 'Мексика', 'na', 'compliant', false, null, '{visa_mastercard,spei}'),

-- LATIN AMERICA
('BR', 'Brazil', 'Бразилия', 'latam', 'compliant', false, null, '{pix,visa_mastercard}'),
('AR', 'Argentina', 'Аргентина', 'latam', 'grey_list', false, null, '{visa_mastercard,crypto}'),
('CO', 'Colombia', 'Колумбия', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('CL', 'Chile', 'Чили', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('PE', 'Peru', 'Перу', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('VE', 'Venezuela', 'Венесуэла', 'latam', 'grey_list', false, null, '{crypto,visa_mastercard}'),
('EC', 'Ecuador', 'Эквадор', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('BO', 'Bolivia', 'Боливия', 'latam', 'grey_list', false, null, '{visa_mastercard}'),
('PY', 'Paraguay', 'Парагвай', 'latam', 'grey_list', false, null, '{visa_mastercard}'),
('UY', 'Uruguay', 'Уругвай', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('CR', 'Costa Rica', 'Коста-Рика', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('GT', 'Guatemala', 'Гватемала', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('PA', 'Panama', 'Панама', 'latam', 'grey_list', false, null, '{visa_mastercard}'),
('CW', 'Curaçao', 'Кюрасао', 'latam', 'compliant', false, null, '{visa_mastercard}'),
('SV', 'El Salvador', 'Сальвадор', 'latam', 'compliant', false, null, '{bitcoin,visa_mastercard}'),

-- CIS
('RU', 'Russia', 'Россия', 'cis', 'grey_list', true, 'OFAC/EU sanctions; MIR/SBP only', '{mir,sbp,crypto}'),
('KZ', 'Kazakhstan', 'Казахстан', 'cis', 'compliant', false, null, '{visa_mastercard,sbp}'),
('UA', 'Ukraine', 'Украина', 'cis', 'compliant', false, null, '{visa_mastercard,crypto}'),
('BY', 'Belarus', 'Беларусь', 'cis', 'grey_list', true, 'EU/US sectoral sanctions', '{visa_mastercard}'),
('UZ', 'Uzbekistan', 'Узбекистан', 'cis', 'grey_list', false, null, '{visa_mastercard}'),
('AZ', 'Azerbaijan', 'Азербайджан', 'cis', 'compliant', false, null, '{visa_mastercard}'),
('GE', 'Georgia', 'Грузия', 'cis', 'compliant', false, null, '{visa_mastercard}'),
('AM', 'Armenia', 'Армения', 'cis', 'compliant', false, null, '{visa_mastercard}'),
('KG', 'Kyrgyzstan', 'Кыргызстан', 'cis', 'grey_list', false, null, '{visa_mastercard}'),
('TJ', 'Tajikistan', 'Таджикистан', 'cis', 'grey_list', false, null, '{visa_mastercard}'),
('TM', 'Turkmenistan', 'Туркменистан', 'cis', 'grey_list', false, null, '{visa_mastercard}'),
('MD', 'Moldova', 'Молдова', 'cis', 'compliant', false, null, '{visa_mastercard}'),

-- MENA
('AE', 'UAE', 'ОАЭ', 'mena', 'compliant', false, null, '{visa_mastercard,crypto}'),
('SA', 'Saudi Arabia', 'Саудовская Аравия', 'mena', 'compliant', false, null, '{visa_mastercard,mada}'),
('QA', 'Qatar', 'Катар', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('KW', 'Kuwait', 'Кувейт', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('BH', 'Bahrain', 'Бахрейн', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('OM', 'Oman', 'Оман', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('JO', 'Jordan', 'Иордания', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('LB', 'Lebanon', 'Ливан', 'mena', 'grey_list', false, null, '{visa_mastercard,cash}'),
('EG', 'Egypt', 'Египет', 'mena', 'grey_list', false, null, '{visa_mastercard,instapay}'),
('MA', 'Morocco', 'Марокко', 'mena', 'grey_list', false, null, '{visa_mastercard}'),
('TN', 'Tunisia', 'Тунис', 'mena', 'compliant', false, null, '{visa_mastercard}'),
('DZ', 'Algeria', 'Алжир', 'mena', 'grey_list', false, null, '{visa_mastercard}'),
('IQ', 'Iraq', 'Ирак', 'mena', 'grey_list', false, null, '{visa_mastercard,cash}'),
('IR', 'Iran', 'Иран', 'mena', 'black_list', true, 'Full OFAC/UN/EU sanctions', null),
('SY', 'Syria', 'Сирия', 'mena', 'black_list', true, 'Full OFAC/EU sanctions', null),
('YE', 'Yemen', 'Йемен', 'mena', 'grey_list', false, null, '{visa_mastercard,cash}'),
('IL', 'Israel', 'Израиль', 'mena', 'compliant', false, null, '{visa_mastercard,sepa}'),
('TR', 'Turkey', 'Турция', 'mena', 'grey_list', false, null, '{visa_mastercard,troy}'),

-- AFRICA
('ZA', 'South Africa', 'ЮАР', 'africa', 'grey_list', false, null, '{visa_mastercard,eft}'),
('NG', 'Nigeria', 'Нигерия', 'africa', 'grey_list', false, null, '{visa_mastercard,crypto,bank_transfer}'),
('KE', 'Kenya', 'Кения', 'africa', 'compliant', false, null, '{m_pesa,visa_mastercard}'),
('GH', 'Ghana', 'Гана', 'africa', 'compliant', false, null, '{mtn_mobile_money,visa_mastercard}'),
('TZ', 'Tanzania', 'Танзания', 'africa', 'compliant', false, null, '{m_pesa,visa_mastercard}'),
('ET', 'Ethiopia', 'Эфиопия', 'africa', 'compliant', false, null, '{visa_mastercard,telebirr}'),
('UG', 'Uganda', 'Уганда', 'africa', 'compliant', false, null, '{mtn_mobile_money,visa_mastercard}'),
('RW', 'Rwanda', 'Руанда', 'africa', 'compliant', false, null, '{mtn_mobile_money,visa_mastercard}'),
('SN', 'Senegal', 'Сенегал', 'africa', 'compliant', false, null, '{orange_money,visa_mastercard}'),
('CI', 'Ivory Coast', 'Кот-д''Ивуар', 'africa', 'compliant', false, null, '{orange_money,mtn_mobile_money}'),
('CM', 'Cameroon', 'Камерун', 'africa', 'compliant', false, null, '{mtn_mobile_money,orange_money}'),
('AO', 'Angola', 'Ангола', 'africa', 'grey_list', false, null, '{visa_mastercard}'),
('ZM', 'Zambia', 'Замбия', 'africa', 'compliant', false, null, '{visa_mastercard,mobile_money}'),
('MZ', 'Mozambique', 'Мозамбик', 'africa', 'grey_list', false, null, '{m_pesa,visa_mastercard}'),

-- APAC
('CN', 'China', 'Китай', 'apac', 'compliant', false, null, '{wechat_pay,alipay,unionpay}'),
('IN', 'India', 'Индия', 'apac', 'compliant', false, null, '{upi,visa_mastercard}'),
('JP', 'Japan', 'Япония', 'apac', 'compliant', false, null, '{visa_mastercard,konbini,paypay}'),
('KR', 'South Korea', 'Южная Корея', 'apac', 'compliant', false, null, '{visa_mastercard,kakaopay}'),
('SG', 'Singapore', 'Сингапур', 'apac', 'compliant', false, null, '{visa_mastercard,paynow,crypto}'),
('AU', 'Australia', 'Австралия', 'apac', 'compliant', false, null, '{visa_mastercard,bpay,osko}'),
('NZ', 'New Zealand', 'Новая Зеландия', 'apac', 'compliant', false, null, '{visa_mastercard}'),
('HK', 'Hong Kong', 'Гонконг', 'apac', 'compliant', false, null, '{visa_mastercard,fps,crypto}'),
('TW', 'Taiwan', 'Тайвань', 'apac', 'compliant', false, null, '{visa_mastercard,linepay}'),
('TH', 'Thailand', 'Таиланд', 'apac', 'compliant', false, null, '{promptpay,visa_mastercard}'),
('MY', 'Malaysia', 'Малайзия', 'apac', 'compliant', false, null, '{duitnow,visa_mastercard}'),
('ID', 'Indonesia', 'Индонезия', 'apac', 'grey_list', false, null, '{gopay,ovo,visa_mastercard}'),
('PH', 'Philippines', 'Филиппины', 'apac', 'grey_list', false, null, '{gcash,visa_mastercard}'),
('VN', 'Vietnam', 'Вьетнам', 'apac', 'grey_list', false, null, '{visa_mastercard,vnpay,momo}'),
('PK', 'Pakistan', 'Пакистан', 'apac', 'grey_list', false, null, '{visa_mastercard,jazzcash,easypaisa}'),
('BD', 'Bangladesh', 'Бангладеш', 'apac', 'grey_list', false, null, '{bkash,visa_mastercard}'),
('LK', 'Sri Lanka', 'Шри-Ланка', 'apac', 'grey_list', false, null, '{visa_mastercard}'),
('NP', 'Nepal', 'Непал', 'apac', 'grey_list', false, null, '{visa_mastercard,esewa}'),
('MM', 'Myanmar', 'Мьянма', 'apac', 'grey_list', false, null, '{kbzpay,visa_mastercard}'),
('KH', 'Cambodia', 'Камбоджа', 'apac', 'grey_list', false, null, '{visa_mastercard,bakong}'),
('KP', 'North Korea', 'Северная Корея', 'apac', 'black_list', true, 'Full UN/OFAC/EU sanctions', null),

-- OCEANIA
('FJ', 'Fiji', 'Фиджи', 'oceania', 'compliant', false, null, '{visa_mastercard}'),
('PG', 'Papua New Guinea', 'Папуа Новая Гвинея', 'oceania', 'grey_list', false, null, '{visa_mastercard}'),

-- OTHER SANCTIONED / BLACKLISTED
('CU', 'Cuba', 'Куба', 'latam', 'compliant', true, 'OFAC comprehensive sanctions', null),
('SD', 'Sudan', 'Судан', 'africa', 'black_list', true, 'OFAC sanctions', null),
('SS', 'South Sudan', 'Южный Судан', 'africa', 'grey_list', false, null, '{m_pesa,visa_mastercard}'),
('LY', 'Libya', 'Ливия', 'africa', 'grey_list', false, null, '{visa_mastercard,cash}'),

-- CRYPTO-FRIENDLY SPECIAL JURISDICTIONS
('CF', 'Central African Republic', 'ЦАР', 'africa', 'grey_list', false, null, '{bitcoin,mobile_money}')
ON CONFLICT (code) DO NOTHING;
